# Generated by Django 4.0.4 on 2022-05-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descript',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
